# Generated by Django 2.0 on 2019-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全國知名', max_length=10, verbose_name='機構標簽'),
        ),
    ]
